# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

image: registry.gitlab.com/catalyst-samba/samba:latest

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

before_script:
  - echo "Build starting (preparing swap)..."
  - if [ $(df -m / --output=avail | tail -n1) -gt 10240 ]; then
      sudo dd if=/dev/zero of=/samba-swap bs=1M count=6144;
      sudo mkswap /samba-swap;
      sudo swapon /samba-swap;
    fi

build_samba:
  stage: build
  tags:
    - docker
  script:
    # this one takes about 4 hours to finish
    - python script/autobuild.py samba            --verbose --tail --testbase /tmp/samba-testbase

build_samba_nt4:
  stage: build
  tags:
    - autobuild
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-nt4        --verbose --tail --testbase /tmp/samba-testbase

build_samba_fileserver:
  stage: build
  tags:
    - autobuild
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-fileserver --verbose --tail --testbase /tmp/samba-testbase

build_samba_ad_dc:
  stage: build
  tags:
    - autobuild
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-ad-dc     --verbose --tail --testbase /tmp/samba-testbase

build_samba_none_env:
  stage: build
  tags:
    - autobuild
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-none-env    --verbose --tail --testbase /tmp/samba-testbase

build_samba_others:
  stage: build
  tags:
    - docker
  script:
    - python script/autobuild.py samba-nopython   --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py samba-systemkrb5 --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py samba-xc         --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py samba-o3         --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py samba-libs       --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py samba-static     --verbose --tail --testbase /tmp/samba-testbase

build_ctdb:
  stage: build
  tags:
    - docker
  script:
    - python script/autobuild.py samba-ctdb       --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py ctdb             --verbose --tail --testbase /tmp/samba-testbase

build_others:
  stage: build
  tags:
    - docker
  script:
    - python script/autobuild.py ldb              --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py pidl             --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py replace          --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py talloc           --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py tdb              --verbose --tail --testbase /tmp/samba-testbase
    - python script/autobuild.py tevent           --verbose --tail --testbase /tmp/samba-testbase

after_script:
  - echo "Build finished!"
