language: c

sudo: true

cache:
  directories:
  - $HOME/.ccache
  
addons:
  apt:
    packages:
      - acl
      - attr
      - autoconf
      - bison
      - build-essential
      - ccache
      - curl
      - debhelper
      - dnsutils
      - docbook-xml
      - docbook-xsl
      - emacs24-nox
      - flex
      - gdb
      - git
      - jed
      - krb5-user
      - libacl1-dev
      - libaio-dev
      - libattr1-dev
      - libblkid-dev
      - libbsd-dev
      - libcap-dev
      - libcups2-dev
      - libgnutls-dev
      - libjson-perl
      - libldap2-dev
      - libncurses5-dev
      - libpam0g-dev
      - libparse-yapp-perl
      - libpopt-dev
      - libreadline-dev
      - perl
      - perl-modules
      - pkg-config
      - python-all-dev
      - python-crypto
      - python-dev
      - python-dnspython
      - python-novaclient
      - screen
      - xsltproc
      - zlib1g-dev

script:
 - sudo apt-get update -qq
 - sudo apt-get install screen git build-essential libacl1-dev libattr1-dev libblkid-dev libgnutls-dev libreadline-dev python-dev libpam0g-dev python-dnspython gdb pkg-config libpopt-dev libldap2-dev dnsutils libbsd-dev attr krb5-user docbook-xsl libcups2-dev acl bison debhelper docbook-xml docbook-xsl flex libaio-dev libbsd-dev libcap-dev libcups2-dev libncurses5-dev libpam0g-dev libpopt-dev libreadline-dev perl perl-modules libparse-yapp-perl pkg-config python-all-dev python-dnspython xsltproc zlib1g-dev autoconf

install:
 - git fetch --unshallow
 - ./script/autobuild.py --tail --testbase=/tmp --ccache=$HOME/.ccache --skip=samba,pidl --instant-start
 

